server {
    listen 80;
    server_name pittylittle.shop www.pittylittle.shop;

    return 301 https://$host$request_uri;
}

server {

    listen 443 ssl;
    http2 on;

    server_name pittylittle.shop www.pittylittle.shop;

    root /var/www/html/pub;
    index index.php;

    ssl_certificate     /etc/letsencrypt/live/pittylittle.shop/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/pittylittle.shop/privkey.pem;

    client_max_body_size 64M;

    location / {
        try_files $uri $uri/ /index.php?$args;
    }

    location /static/ {
        expires max;
        access_log off;

        location ~ ^/static/version {
            rewrite ^/static/(version\d*/)?(.*)$ /static/$2 last;
        }

        try_files $uri $uri/ /static.php?resource=$uri&$args;
    }

    location /media/ {
        expires max;
        access_log off;

        try_files $uri $uri/ /get.php?$args;
    }

    location ~ \.php$ {

        try_files $uri =404;

        include fastcgi_params;

        fastcgi_pass php:9000;
        fastcgi_index index.php;

        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param HTTPS on;

        fastcgi_read_timeout 600;

        fastcgi_buffer_size 128k;
        fastcgi_buffers 16 64k;
        fastcgi_busy_buffers_size 256k;
    }

    location ~ /\.(?!well-known).* {
        deny all;
    }
}
