name: Deploy Magento to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.2.0

        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}

          script: |
            cd ~/magento-stack

            echo "Pulling latest code..."
            git pull origin main

            echo "Restarting containers..."
            docker compose up -d

            echo "Flushing Magento cache..."
            docker exec magento-php bash -c "cd /var/www/html && php bin/magento cache:flush"

            echo "Deployment completed successfully."
